"""add company_id

Revision ID: e6dc129c8c81
Revises: b97d6d4955e6
Create Date: 2018-07-28 22:53:03.820933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6dc129c8c81'
down_revision = 'b97d6d4955e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobwanted', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobwanted', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobwanted', type_='foreignkey')
    op.drop_column('jobwanted', 'company_id')
    # ### end Alembic commands ###
